### ISSUE TITLE
text_to_speech_v1.go:81:41: not enough arguments in call to core.NewBaseService

### ISSUE THREAD

**Issue by jaszhou** [watson-developer-cloud/go-sdk#75]
**Overview**
When I try to import the module of github.com/watson-developer-cloud, the `go test` command gives the following error:

go test
```
github.com/watson-developer-cloud/go-sdk/texttospeechv1
../../../go/pkg/mod/github.com/watson-developer-cloud/go-sdk@v1.4.1/texttospeechv1/text_to_speech_v1.go:81:41: not enough arguments in call to core.NewBaseService
	have (*core.ServiceOptions)
	want (*core.ServiceOptions, string, string)
```

**Expected behavior**
The `go test` command should give no error

**Actual behavior**
The above error

**How to reproduce**
Create a new folder 
Go to the new folder and create a hello world golang script
Import the module of `github.com/watson-developer-cloud/go-sdk/texttospeechv1`
Run `go test`

**SDK Version**
```
github.com/watson-developer-cloud/go-sdk@v1.4.1
```

**Additional information:**
- OS: MacOS 10.14.6 
- go version go1.14 darwin/amd64

**Comment by jaszhou** [comment]
Refer to this blog for the answer:

https://www.ibm.com/cloud/blog/call-the-watson-speech-service-with-watson-sdk-for-golang

**Comment by padamstx** [comment]
What sort of Go dependency manager are you using for your application?   dep, go modules, something else?

The error seems to indicate that the go-sdk and go-sdk-core modules that you have are not compatible.  Version 1.4.1 of the go-sdk requires v2.1.1 of the go-sdk-core module.
If you are using Go modules, could you try replacing the version # associated with the go-sdk-core to be "v2.1.1".  Otherwise, if you're using "dep", perhaps you could try defining an explicit dependency on go-sdk-core v2.1.1.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
